# Generated by Django 6.0.2 on 2026-02-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='etat',
            field=models.CharField(blank=True, choices=[('en_stock', 'En stock'), ('reserve', 'Réservé'), ('en_transit', 'En transit'), ('expedie', 'Expédié'), ('perdu', 'Perdu'), ('detruire', 'À détruire')], max_length=30, null=True),
        ),
    ]
