# Generated by Django 6.0.1 on 2026-02-24 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_lots_etat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historiquetracabilites',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.lots'),
        ),
        migrations.AlterField(
            model_name='historiquetracabilites',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_tracabilites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lots',
            name='producteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.producteurs'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.produits'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lots',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.zoneentrepots'),
        ),
        migrations.AlterField(
            model_name='mouvementstocks',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.lots'),
        ),
        migrations.AlterField(
            model_name='mouvementstocks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvement_stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mouvementstocks',
            name='zone_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvementstocks_zone_destination_set', to='gestion.zoneentrepots'),
        ),
        migrations.AlterField(
            model_name='mouvementstocks',
            name='zone_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.zoneentrepots'),
        ),
        migrations.AlterField(
            model_name='ventes',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.clients'),
        ),
        migrations.AlterField(
            model_name='ventes',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.lots'),
        ),
        migrations.AlterField(
            model_name='ventes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zoneentrepots',
            name='entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entrepots'),
        ),
    ]
