# Generated by Django 6.0.2 on 2026-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_clients_email_alter_historiquetracabilites_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepots',
            name='statut',
            field=models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lots',
            name='etat',
            field=models.CharField(blank=True, choices=[('EN_STOCK', 'En stock'), ('PARTIELLEMENT_SORTI', 'Partiellement sorti'), ('EPUISE', 'Épuisé')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lots',
            name='qualite',
            field=models.CharField(blank=True, choices=[('PREMIUM', 'Premium'), ('STANDARD', 'Standard'), ('ECONOMIQUE', 'Économique')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementstocks',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('AJUSTEMENT', 'Ajustement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producteurs',
            name='statut',
            field=models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producteurs',
            name='type_producteur',
            field=models.CharField(blank=True, choices=[('INDIVIDUEL', 'Individuel'), ('COOPERATIVE', 'Coopérative'), ('ENTREPRISE', 'Entreprise')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ventes',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement'), ('MOBILE_MONEY', 'Mobile Money')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zoneentrepots',
            name='statut',
            field=models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], max_length=30, null=True),
        ),
    ]
