# Generated by Django 6.0 on 2026-01-11 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=150, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('date_inscription', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'db_table_comment': 'Clients acheteurs',
            },
        ),
        migrations.CreateModel(
            name='Producteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('localisation', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_identification', models.CharField(blank=True, max_length=50, null=True)),
                ('type_producteur', models.CharField(blank=True, max_length=30, null=True)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inscription', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producteurs',
                'db_table_comment': 'Producteurs de noix de cajou',
            },
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('unite', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'produits',
                'db_table_comment': 'Catalogue des produits',
            },
        ),
        migrations.CreateModel(
            name='Entrepots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=150, null=True)),
                ('capacite_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seuil_critique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_disponible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(blank=True, max_length=30, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('date_maj', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrepots_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entrepots',
                'db_table_comment': 'Entrepôts de stockage',
            },
        ),
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_lot', models.CharField(max_length=50, unique=True)),
                ('quantite_initiale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_restante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qualite', models.CharField(blank=True, max_length=50, null=True)),
                ('etat', models.CharField(blank=True, max_length=30, null=True)),
                ('date_reception', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lots', to=settings.AUTH_USER_MODEL)),
                ('producteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.producteurs')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.produits')),
            ],
            options={
                'db_table': 'lots',
                'db_table_comment': 'Lots de produits avec traçabilité',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueTracabilites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(blank=True, null=True)),
                ('type_action', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='historique_tracabilites', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.lots')),
            ],
            options={
                'db_table': 'historique_tracabilites',
                'db_table_comment': "Historique d'audit et traçabilité",
            },
        ),
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vente', models.CharField(max_length=50, unique=True)),
                ('date_vente', models.DateTimeField(blank=True, null=True)),
                ('quantite_vendue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mode_paiement', models.CharField(blank=True, max_length=30, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.clients')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.lots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ventes',
                'db_table_comment': 'Ventes enregistrées',
            },
        ),
        migrations.CreateModel(
            name='ZoneEntrepots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(blank=True, max_length=30, null=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.entrepots')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_entrepots_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zone_entrepots',
                'db_table_comment': "Zones à l'intérieur des entrepôts",
                'unique_together': {('nom', 'entrepot')},
            },
        ),
        migrations.CreateModel(
            name='MouvementStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mouvement', models.DateTimeField(blank=True, null=True)),
                ('type_mouvement', models.CharField(max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.CharField(blank=True, max_length=200, null=True)),
                ('valide', models.BooleanField(blank=True, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.lots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mouvement_stocks', to=settings.AUTH_USER_MODEL)),
                ('zone_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mouvementstocks_zone_destination_set', to='gestion.zoneentrepots')),
                ('zone_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.zoneentrepots')),
            ],
            options={
                'db_table': 'mouvement_stocks',
                'db_table_comment': 'Journal des mouvements de stock',
            },
        ),
        migrations.AddField(
            model_name='lots',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.zoneentrepots'),
        ),
    ]
